apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-spark
  namespace: log-analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-spark-role-binding
  namespace: log-analytics
subjects:
- kind: ServiceAccount
  name: spark-operator-spark
  namespace: log-analytics
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
