apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-web-manager
  namespace: log-analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: log-analytics
  name: log-manager-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-manager-binding
  namespace: log-analytics
subjects:
- kind: ServiceAccount
  name: log-web-manager
  namespace: log-analytics
roleRef:
  kind: Role
  name: log-manager-role
  apiGroup: rbac.authorization.k8s.io
