apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-web-manager
  namespace: log-analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scaler
  namespace: log-analytics
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-web-manager-scaler
  namespace: log-analytics
subjects:
  - kind: ServiceAccount
    name: log-web-manager
    namespace: log-analytics
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io
